### ISSUE TITLE
email types aren't validated

### ISSUE THREAD

**Issue by poechsel** [tozti/tozti#18]
I just found a pretty *annoying* bug. When a resource is created (or updated), the validator doesn't work for `email` types
Exemple (update of a ressource):
```
>>>  create_resource(type="core/user", attributes={"name": "f", "email":"a@a.com", "login":"foo"})
>>>  update_resource(id=<id>, type="core/user", attributes={"email":"pwned"})
```
In theory the update should fail because `pwned` entry is not an email.

The more surprising is that `Jsonschema` is supposed to validate emails (https://python-jsonschema.readthedocs.io/en/latest/validate/#jsonschema.Draft4Validator)

**Comment by Lapin0t** [comment]
Ok, so the problem is explained juste after that in their [doc](https://python-jsonschema.readthedocs.io/en/latest/validate/#validating-formats): by default no format is validated.
